#! /bin/env bash

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-scale ~/.wallpaper/goals.png &

picom &

# scratchterm
urxvt -name scratchterm &
sleep 0.2
id=$(xdotool search --classname scratchterm)
bspc node "$id" --flag sticky
bspc node "$id" --flag hidden
bspc node "$id" --state floating

~/.config/bspwm/masterlayout.sh &
bspc config external_rules_command ~/.config/bspwm/external_rules.sh
bspc config split_ratio             0.50
bspc config removal_adjustment      false

echo "Start" >> /home/andreas/foo.txt
echo ${BSPWMMASTER:-west} >> /home/andreas/foo.txt
echo ${BSPWMMASTER} >> /home/andreas/foo.txt

~/.config/polybar/launch.sh &

